<?php
$page_name = 'seat selection page';  // Set the current page name
include('../pages/header.php');
?>
<style>
    .seat {
        width: 50px;
        height: 50px;
        margin: 5px;
        text-align: center;
        border: 1px solid #ccc;
        cursor: pointer;
    }

    .available {
        background-color: #e0e0e0;
    }

    .selected {
        background-color: #4caf50;
        color: white;
    }

    .occupied {
        background-color: #f44336;
        color: white;
    }

    .aisle {
        width: 10px;
        display: inline-block;
        background-color: #fff;
    }
</style>
</head>

<body>
    <!-- <div class="container">
    <h2 class="seat-selection-title">Select Your Seat - Post Bus Malawi</h2>
    
   
    <form action="process-seat.php" method="POST">
        <div class="bus-layout">
            <div class="bus-front">Driver</div>

            <div class="driver-area">
                <div class="driver-seat">🚌</div>
            </div>

            <div class="seats-container" id="seatsContainer">
                Seats will be generated by JavaScript
            </div>

            <div class="legend">
                <div class="legend-item">
                    <div class="legend-color available-color"></div>
                    <span>Available</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color selected-color"></div>
                    <span>Selected</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color occupied-color"></div>
                    <span>Occupied</span>
                </div>
            </div>
        </div>

        <div class="booking-summary">
            <h3>Booking Summary</h3>
            <div class="malawi-logo">
                <img src="../images/m.webp" alt="Malawi Corporation Logo" class="seatlog">
            </div>
            <div class="price-details">
                <div class="price-row">
                    <span>Base Fare:</span>
                    <span>MWK 35,000</span>
                </div>
                <div class="price-row" id="selectedSeatsText">
                    <span>Selected Seats:</span>
                    <span>None</span>
                </div>
                <div class="price-row">
                    <span>Booking Fee:</span>
                    <span>MWK 2,500</span>
                </div>
                <div class="price-row">
                    <span>Tax:</span>
                    <span>MWK 3,750</span>
                </div>
                <div class="price-row total-price">
                    <span>Total:</span>
                    <span id="totalPrice">MWK 41,250</span>
                </div>
            </div>
        </div>

        <div class="button-container">
            <button type="button" class="back-button" id="backButton">Back to Selection</button>
            <button type="submit" class="pay-button" id="payButton" disabled>Proceed to Payment</button>
        </div>
    </form>
</div> -->
    <div class="container">
        <h2 class="seat-selection-title">Select Your Seat - Post Bus Malawi</h2>

        <!-- Start of the form -->
        <form action="process-seat.php" method="POST">
            <div class="bus-layout">
                <div class="bus-front">Driver</div>

                <div class="driver-area">
                    <div class="driver-seat">🚌</div>
                </div>

                <div class="seats-container" id="seatsContainer">
                    <!-- Seats will be generated by JavaScript -->
                </div>

                <div class="legend">
                    <div class="legend-item">
                        <div class="legend-color available-color"></div>
                        <span>Available</span>
                    </div>
                    <div class="legend-item">
                        <div class="legend-color selected-color"></div>
                        <span>Selected</span>
                    </div>
                    <div class="legend-item">
                        <div class="legend-color occupied-color"></div>
                        <span>Occupied</span>
                    </div>
                </div>
            </div>

            <div class="booking-summary">
                <h3>Booking Summary</h3>
                <div class="malawi-logo">
                    <img src="../images/m.webp" alt="Malawi Corporation Logo" class="seatlog">
                </div>
                <div class="price-details">
                    <div class="price-row">
                        <span>Base Fare:</span>
                        <span>MWK 35,000</span>
                    </div>
                    <div class="price-row" id="selectedSeatsText">
                        <span>Selected Seats:</span>
                        <span>None</span>
                    </div>
                    <div class="price-row">
                        <span>Booking Fee:</span>
                        <span>MWK 2,500</span>
                    </div>
                    <div class="price-row">
                        <span>Tax:</span>
                        <span>MWK 3,750</span>
                    </div>
                    <div class="price-row total-price">
                        <span>Total:</span>
                        <span id="totalPrice">MWK 41,250</span>
                    </div>
                </div>
            </div>

            <div class="button-container">
                <button type="button" class="back-button" id="backButton">Back to Selection</button>
                <button type="submit" class="pay-button" id="payButton" disabled>Proceed to Payment</button>
            </div>
        </form>
        <!-- End of the form -->
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const seatsContainer = document.getElementById('seatsContainer');
            const payButton = document.getElementById('payButton');
            const backButton = document.getElementById('backButton');
            const totalPriceElement = document.getElementById('totalPrice');
            const selectedSeatsTextElement = document.getElementById('selectedSeatsText');

            // Configuration
            const rows = 10;
            const seatsPerRow = 4;
            const baseFare = 35000;
            const bookingFee = 2500;
            const tax = 3750;

            // Pre-occupied seats
            const occupiedSeats = ['1A', '2C', '3D', '5B', '7A', '8D', '9C'];

            // Selected seats
            let selectedSeats = [];

            // Get booking ID from sessionStorage or URL
            function getBookingId() {
                console.log('Getting booking ID from sessionStorage'.sessionStorage.getItem('booking_code'));


                const urlParams = new URLSearchParams(window.location.search);
                const bookingCode = urlParams.get('booking_id');

                if (!bookingCode) {
                    const urlParams = new URLSearchParams(window.location.search);
                    bookingCode = urlParams.get('booking_code');

                    if (bookingCode) {
                        sessionStorage.setItem('booking_code', bookingCode); // Store for later use
                    }
                }

                console.log("Retrieved booking code:", bookingCode || "None"); // Debugging
                return bookingCode || null;
            }

            // Generate seats
            for (let row = 1; row <= rows; row++) {
                const rowContainer = document.createElement('div');
                rowContainer.className = 'seat-row';

                for (let seat = 1; seat <= seatsPerRow; seat++) {
                    const seatElement = document.createElement('div');

                    let seatLetter = ['A', 'B', 'C', 'D'][seat - 1];
                    const seatId = `${row}${seatLetter}`;
                    seatElement.id = seatId;
                    seatElement.className = 'seat';
                    seatElement.textContent = seatId;

                    if (occupiedSeats.includes(seatId)) {
                        seatElement.classList.add('occupied');
                    } else {
                        seatElement.classList.add('available');
                        seatElement.addEventListener('click', function() {
                            toggleSeatSelection(seatId);
                        });
                    }

                    rowContainer.appendChild(seatElement);

                    if (seat === 2) {
                        const aisleElement = document.createElement('div');
                        aisleElement.className = 'seat aisle';
                        rowContainer.appendChild(aisleElement);
                    }
                }
                seatsContainer.appendChild(rowContainer);
            }

            // Toggle seat selection
            function toggleSeatSelection(seatId) {
                const seatElement = document.getElementById(seatId);
                if (!seatElement) return;

                if (seatElement.classList.contains('selected')) {
                    seatElement.classList.remove('selected');
                    seatElement.classList.add('available');
                    selectedSeats = selectedSeats.filter(id => id !== seatId);
                } else {
                    seatElement.classList.remove('available');
                    seatElement.classList.add('selected');
                    selectedSeats.push(seatId);
                }

                updateBookingSummary();
            }

            // Update booking summary
            function updateBookingSummary() {
                const seatPrice = baseFare;
                const seatsTotal = selectedSeats.length * seatPrice;
                const total = seatsTotal + bookingFee + tax;

                totalPriceElement.textContent = formatCurrency(total);

                if (selectedSeats.length > 0) {
                    selectedSeatsTextElement.innerHTML = `
                <span>Selected Seats (${selectedSeats.length}):</span>
                <span>${selectedSeats.join(', ')} - ${formatCurrency(seatsTotal)}</span>
            `;

                    let hiddenInput = document.getElementById('selectedSeatsInput');
                    if (!hiddenInput) {
                        hiddenInput = document.createElement('input');
                        hiddenInput.type = 'hidden';
                        hiddenInput.id = 'selectedSeatsInput';
                        hiddenInput.name = 'selected_seats';
                        document.querySelector('form')?.appendChild(hiddenInput);
                    }
                    hiddenInput.value = JSON.stringify(selectedSeats);

                    payButton.disabled = false;
                } else {
                    selectedSeatsTextElement.innerHTML = `
                <span>Selected Seats:</span>
                <span>None</span>
            `;
                    payButton.disabled = true;
                }
            }

            function formatCurrency(amount) {
                return 'MWK ' + amount.toLocaleString('en-US');
            }

            // Pay button event listener (ensures it exists)
            if (payButton) {
                payButton.addEventListener('click', function(e) {
                    e.preventDefault();

                    if (selectedSeats.length === 0) {
                        alert("Please select at least one seat before proceeding.");
                        return;
                    }

                    const bookingCode = getBookingId();

                    if (!bookingCode) {
                        console.error("Error: Booking code not found. Check URL or sessionStorage.");
                        alert("Booking code not found. Please start a new booking.");
                        sessionStorage.removeItem('booking_code'); // Clear invalid stored data
                        window.location.href = 'booking.php'; // Redirect to new booking
                        return;
                    }

                    const requestData = {
                        booking_code: bookingCode,
                        selected_seats: selectedSeats
                    };

                    console.log("Sending to server:", requestData);

                    fetch('process-seat.php', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json'
                            },
                            body: JSON.stringify(requestData)
                        })
                        .then(response => {
                            if (!response.ok) throw new Error("Server error: " + response.status);
                            return response.json();
                        })
                        .then(data => {
                            console.log("Processed response:", data);
                            if (data.success) {
                                window.location.href = `payment.php?booking_code=${bookingCode}`;
                            } else {
                                alert("Booking Failed: " + data.message);
                            }
                        })
                        .catch(error => {
                            console.error('Fetch Error:', error);
                            alert("An error occurred. Please try again. Details: " + error.message);
                        });
                });
            }
        });
    </script>


    <script src="../script/java.js"></script>
    <script src="../script/script.js"></script>

    <?php
    include('../pages/footer.php');
    ?>

    <!-- <script>
        document.addEventListener('DOMContentLoaded', function() {
            const seatsContainer = document.getElementById('seatsContainer');
            const payButton = document.getElementById('payButton');
            const backButton = document.getElementById('backButton');
            const totalPriceElement = document.getElementById('totalPrice');
            const selectedSeatsTextElement = document.getElementById('selectedSeatsText');

            // Configuration
            const rows = 10;
            const seatsPerRow = 4; // 2 on each side of aisle
            const baseFare = 35000; // in Malawi Kwacha
            const bookingFee = 2500;
            const tax = 3750;

            // Pre-occupied seats
            const occupiedSeats = ['1A', '2C', '3D', '5B', '7A', '8D', '9C'];

            // Selected seats
            let selectedSeats = [];

            // Generate seats
            for (let row = 1; row <= rows; row++) {
                for (let seat = 1; seat <= seatsPerRow; seat++) {
                    const seatElement = document.createElement('div');

                    // Determine seat letter (A, B, C, D)
                    let seatLetter;
                    if (seat === 1) seatLetter = 'A';
                    else if (seat === 2) seatLetter = 'B';
                    else if (seat === 3) seatLetter = 'C';
                    else if (seat === 4) seatLetter = 'D';

                    const seatId = `${row}${seatLetter}`;
                    seatElement.id = seatId;
                    seatElement.className = 'seat';
                    seatElement.textContent = seatId;

                    // Check if seat is occupied
                    if (occupiedSeats.includes(seatId)) {
                        seatElement.classList.add('occupied');
                    } else {
                        seatElement.classList.add('available');

                        // Add click event to available seats
                        seatElement.addEventListener('click', function() {
                            toggleSeatSelection(seatId);
                        });
                    }

                    seatsContainer.appendChild(seatElement);

                    // Add aisle after the second seat in each row
                    if (seat === 2) {
                        const aisleElement = document.createElement('div');
                        aisleElement.className = 'seat aisle';
                        seatsContainer.appendChild(aisleElement);
                    }
                }
            }

            // Toggle seat selection
            function toggleSeatSelection(seatId) {
                const seatElement = document.getElementById(seatId);

                if (seatElement.classList.contains('selected')) {
                    // Deselect
                    seatElement.classList.remove('selected');
                    seatElement.classList.add('available');
                    selectedSeats = selectedSeats.filter(id => id !== seatId);
                } else {
                    // Select
                    seatElement.classList.remove('available');
                    seatElement.classList.add('selected');
                    selectedSeats.push(seatId);
                }

                updateBookingSummary();
            }

            // Format currency for Malawi Kwacha
            function formatCurrency(amount) {
                return 'MWK ' + amount.toLocaleString('en-US');
            }

            // Update booking summary
            function updateBookingSummary() {
                const seatPrice = baseFare;
                const seatsTotal = selectedSeats.length * seatPrice;
                const total = seatsTotal + bookingFee + tax;

                totalPriceElement.textContent = formatCurrency(total);

                if (selectedSeats.length > 0) {
                    selectedSeatsTextElement.innerHTML = `
                    <span>Selected Seats (${selectedSeats.length}):</span>
                    <span>${selectedSeats.join(', ')} - ${formatCurrency(seatsTotal)}</span>
                `;
                    payButton.disabled = false;
                } else {
                    selectedSeatsTextElement.innerHTML = `
                    <span>Selected Seats:</span>
                    <span>None</span>
                `;
                    payButton.disabled = true;
                }
            }

            // Pay button click event
            payButton.addEventListener('click', function() {
                if (selectedSeats.length > 0) {
                    // Store selected seats in session/local storage if needed
                    localStorage.setItem('selectedSeats', JSON.stringify(selectedSeats));
                    localStorage.setItem('totalAmount', totalPriceElement.textContent);

                    // Redirect to payment page
                    window.location.href = 'payment.php';
                }
            });

            // Back button click event
            backButton.addEventListener('click', function() {
                window.location.href = 'booking.php';
            });
        });
        fetch('process-seat.php', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    booking_id: 123456, // Replace with actual booking ID
                    selected_seats: ["1A", "2B", "3C"] // Replace with actual seat selection
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    window.location.href = `payment.php?booking_id=${data.booking_id}`;
                } else {
                    console.error("Error:", data.message, "SQL Error:", data.error);
                    alert("Booking Failed: " + data.message);
                }
            })
            .catch(error => console.error('Fetch Error:', error));
    </script> -->
</body>

</html>
// <script>
    // //     document.addEventListener('DOMContentLoaded', function() {
    //         const seatsContainer = document.getElementById('seatsContainer');
    //         const payButton = document.getElementById('payButton');
    //         const backButton = document.getElementById('backButton');
    //         const totalPriceElement = document.getElementById('totalPrice');
    //         const selectedSeatsTextElement = document.getElementById('selectedSeatsText');

    //         // Configuration
    //         const rows = 10;
    //         const seatsPerRow = 4; // 2 on each side of aisle
    //         const baseFare = 35000; // in Malawi Kwacha
    //         const bookingFee = 2500;
    //         const tax = 3750;

    //         // Pre-occupied seats
    //         const occupiedSeats = ['1A', '2C', '3D', '5B', '7A', '8D', '9C'];

    //         // Selected seats
    //         let selectedSeats = [];

    //         // Generate seats
    //         for (let row = 1; row <= rows; row++) {
    //             for (let seat = 1; seat <= seatsPerRow; seat++) {
    //                 const seatElement = document.createElement('div');

    //                 // Determine seat letter (A, B, C, D)
    //                 let seatLetter;
    //                 if (seat === 1) seatLetter = 'A';
    //                 else if (seat === 2) seatLetter = 'B';
    //                 else if (seat === 3) seatLetter = 'C';
    //                 else if (seat === 4) seatLetter = 'D';

    //                 const seatId = `${row}${seatLetter}`;
    //                 seatElement.id = seatId;
    //                 seatElement.className = 'seat';
    //                 seatElement.textContent = seatId;

    //                 // Check if seat is occupied
    //                 if (occupiedSeats.includes(seatId)) {
    //                     seatElement.classList.add('occupied');
    //                 } else {
    //                     seatElement.classList.add('available');

    //                     // Add click event to available seats
    //                     seatElement.addEventListener('click', function() {
    //                         toggleSeatSelection(seatId);
    //                     });
    //                 }

    //                 seatsContainer.appendChild(seatElement);

    //                 // Add aisle after the second seat in each row
    //                 if (seat === 2) {
    //                     const aisleElement = document.createElement('div');
    //                     aisleElement.className = 'seat aisle';
    //                     seatsContainer.appendChild(aisleElement);
    //                 }
    //             }
    //         }

    //         // Toggle seat selection
    //         function toggleSeatSelection(seatId) {
    //             const seatElement = document.getElementById(seatId);

    //             if (seatElement.classList.contains('selected')) {
    //                 // Deselect
    //                 seatElement.classList.remove('selected');
    //                 seatElement.classList.add('available');
    //                 selectedSeats = selectedSeats.filter(id => id !== seatId);
    //             } else {
    //                 // Select
    //                 seatElement.classList.remove('available');
    //                 seatElement.classList.add('selected');
    //                 selectedSeats.push(seatId);
    //             }

    //             updateBookingSummary();
    //         }

    //         // Format currency for Malawi Kwacha
    //         function formatCurrency(amount) {
    //             return 'MWK ' + amount.toLocaleString('en-US');
    //         }

    //         // Update booking summary
    //         function updateBookingSummary() {
    //             const seatPrice = baseFare;
    //             const seatsTotal = selectedSeats.length * seatPrice;
    //             const total = seatsTotal + bookingFee + tax;

    //             totalPriceElement.textContent = formatCurrency(total);

    //             if (selectedSeats.length > 0) {
    //                 selectedSeatsTextElement.innerHTML = `
    //                     <span>Selected Seats (${selectedSeats.length}):</span>
    //                     <span>${selectedSeats.join(', ')} - ${formatCurrency(seatsTotal)}</span>
    //                 `;
    //                 payButton.disabled = false;
    //             } else {
    //                 selectedSeatsTextElement.innerHTML = `
    //                     <span>Selected Seats:</span>
    //                     <span>None</span>
    //                 `;
    //                 payButton.disabled = true;
    //             }
    //         }

    //         // Pay button click event
    //         payButton.addEventListener('click', function() {
    //             if (selectedSeats.length > 0) {
    //                 // Send selected seats to the server (process-seat.php)
    //                 fetch('process-seat.php', {
    //                     method: 'POST',
    //                     headers: { 'Content-Type': 'application/json' },
    //                     body: JSON.stringify({
    //                         booking_id: 123456, // Replace with actual booking ID
    //                         selected_seats: selectedSeats // Ensure this is the correct variable with selected seats
    //                     })
    //                 })
    //                 .then(response => response.json())
    //                 .then(data => {
    //                     if (data.success) {
    //                         window.location.href = `payment.php?booking_id=${data.booking_id}`;
    //                     } else {
    //                         console.error("Error:", data.message);
    //                         alert("Booking Failed: " + data.message);
    //                     }
    //                 })
    //                 .catch(error => console.error('Fetch Error:', error));
    //             }
    //         });

    //         // Back button click event
    //         backButton.addEventListener('click', function() {
    //             window.location.href = 'booking.php';
    //         });
    //     });
    // 
</script>