<?php
$page_name = 'privacy';  // Set the current page name
include('../pages/header.php');



?>
<style>
    body {
        font-family: 'Roboto', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
    }

    .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
    }

    .seat-selection-title {
        text-align: center;
        color: #2C5282;
        margin-bottom: 30px;
        font-size: 2em;
    }

    .bus-layout {
        background-color: white;
        border-radius: 8px;
        padding: 20px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

    .bus-front {
        text-align: center;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .driver-area {
        text-align: center;
        margin-bottom: 30px;
    }

    .driver-seat {
        display: inline-block;
        font-size: 24px;
        font-weight: bold;
    }

    .seats-container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .seat-row {
        display: flex;
        margin-bottom: 15px;
        justify-content: center;
        align-items: center;
    }

    .seat {
        width: 50px;
        height: 50px;
        margin: 8px;
        text-align: center;
        line-height: 50px;
        border: 2px solid #ccc;
        border-radius: 8px;
        font-weight: bold;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease, transform 0.3s ease;
    }

    .seat:hover {
        transform: scale(1.1);
    }

    .available {
        background-color: #e0e0e0;
    }

    .available:hover {
        background-color: #d0d0d0;
    }

    .selected {
        background-color: #2C5282;
        color: white;
    }

    .occupied {
        background-color: #f44336;
        color: white;
        cursor: not-allowed;
    }

    .aisle {
        width: 20px;
        height: 50px;
        background-color: transparent;
    }

    .legend {
        display: flex;
        justify-content: center;
        margin-top: 30px;
        gap: 20px;
    }

    .legend-item {
        display: flex;
        align-items: center;
        gap: 5px;
    }

    .legend-color {
        width: 20px;
        height: 20px;
        border-radius: 3px;
    }

    .available-color {
        background-color: #e0e0e0;
    }

    .selected-color {
        background-color: #2C5282;
    }

    .occupied-color {
        background-color: #f44336;
    }

    .booking-summary {
        background-color: white;
        border-radius: 8px;
        padding: 20px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

    .booking-summary h3 {
        margin-top: 0;
        color: #2C5282;
    }

    .malawi-logo {
        text-align: center;
        margin: 20px 0;
    }

    .seatlog {
        max-width: 100px;
    }

    .price-details {
        border-top: 1px solid #eee;
        padding-top: 15px;
    }

    .price-row {
        display: flex;
        justify-content: space-between;
        margin-bottom: 10px;
    }

    .total-price {
        font-weight: bold;
        font-size: 1.2em;
        margin-top: 15px;
        padding-top: 10px;
        border-top: 1px solid #eee;
    }

    .button-container {
        display: flex;
        justify-content: space-between;
        margin-top: 20px;
    }

    .back-button,
    .pay-button {
        padding: 12px 24px;
        border: none;
        border-radius: 4px;
        font-weight: bold;
        cursor: pointer;
        font-size: 16px;
    }

    .back-button {
        background-color: #e0e0e0;
        color: #333;
    }

    .back-button:hover {
        background-color: #d0d0d0;
    }

    .pay-button {
        background-color: #2C5282;
        color: white;
    }

    .pay-button:disabled {
        background-color: #cccccc;
        cursor: not-allowed;
    }

    .pay-button:not(:disabled):hover {
        background-color: #1a365d;
    }
</style>
</head>

<body>
    <div class="container">
        <h2 class="seat-selection-title">Select Your Seat - Post Bus Malawi</h2>

        <div class="bus-layout">
            <div class="bus-front">Driver</div>
            <div class="driver-area">
                <div class="driver-seat">🚌</div>
            </div>
            <div class="seats-container" id="seatsContainer">
                <!-- Seats will be generated by JavaScript -->
            </div>
            <div class="legend">
                <div class="legend-item">
                    <div class="legend-color available-color"></div>
                    <span>Available</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color selected-color"></div>
                    <span>Selected</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color occupied-color"></div>
                    <span>Occupied</span>
                </div>
            </div>
        </div>

        <div class="booking-summary">
            <h3>Booking Summary</h3>
            <div class="malawi-logo">
                <img src="../images/m.webp" alt="Malawi Corporation Logo" class="seatlog">
            </div>
            <div class="price-details">
                <div class="price-row">
                    <span>Base Fare:</span>
                    <span>MWK 35,000</span>
                </div>
                <div class="price-row" id="selectedSeatsText">
                    <span>Selected Seats:</span>
                    <span>None</span>
                </div>
                <div class="price-row">
                    <span>Booking Fee:</span>
                    <span>MWK 2,500</span>
                </div>
                <div class="price-row">
                    <span>Tax:</span>
                    <span>MWK 3,750</span>
                </div>
                <div class="price-row total-price">
                    <span>Total:</span>
                    <span id="totalPrice">MWK 41,250</span>
                </div>
            </div>
        </div>

        <div class="button-container">
            <button type="button" class="back-button" id="backButton">Back to Selection</button>
            <button type="button" class="pay-button" id="payButton" disabled>Proceed to Payment</button>
        </div>
    </div>
    <?php include('../pages/footer.php'); ?>

    <script>
    // Configuration
    const config = {
        rows: 10,
        seatsPerRow: 4,
        baseFare: 35000,
        bookingFee: 2500,
        tax: 3750,
        occupiedSeats: ['1A', '2C', '3D', '5B', '7A', '8D']
    };

    // State
    let selectedSeats = [];
    function getBookingCodeFromUrl() {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get('booking_code');
    }

    // Assign booking code t    o bookingId
    let bookingId = getBookingCodeFromUrl();

    // DOM Elements
    const elements = {
        seatsContainer: document.getElementById('seatsContainer'),
        selectedSeatsText: document.getElementById('selectedSeatsText'),
        totalPrice: document.getElementById('totalPrice'),
        payButton: document.getElementById('payButton'),
        backButton: document.getElementById('backButton')
    };

    // Initialize on DOM load
    document.addEventListener('DOMContentLoaded', () => {
        renderSeats();
        updateSummary();
        
        elements.payButton.addEventListener('click', handlePayment);
        elements.backButton.addEventListener('click', () => {
            window.location.href = 'selection.php';
        });
    });

    // Seat selection handler
    function toggleSeat(seatId) {
        const index = selectedSeats.indexOf(seatId);
        
        if (index === -1) {
            selectedSeats.push(seatId);
        } else {
            selectedSeats.splice(index, 1);
        }
        
        updateSeatUI(seatId);
        updateSummary();
    }

    // Update seat visual state
    function updateSeatUI(seatId) {
        const seatElement = document.getElementById(`seat-${seatId}`);
        if (!seatElement) return;
        
        seatElement.classList.toggle('selected', selectedSeats.includes(seatId));
    }

    // Calculate total price
    function calculateTotal() {
        const seatsTotal = selectedSeats.length * config.baseFare;
        return seatsTotal + config.bookingFee + config.tax;
    }

    // Update summary display
    function updateSummary() {
        const total = calculateTotal();
        const hasSeats = selectedSeats.length > 0;
        
        elements.totalPrice.textContent = `MWK ${total.toLocaleString()}`;
        elements.selectedSeatsText.innerHTML = hasSeats
            ? `<span>Selected Seats (${selectedSeats.length}):</span> 
               <span>${selectedSeats.join(', ')} - MWK ${(selectedSeats.length * config.baseFare).toLocaleString()}</span>`
            : '<span>Selected Seats:</span><span>None</span>';
            
        elements.payButton.disabled = !hasSeats;
    }

    // Render all seats
    function renderSeats() {
        elements.seatsContainer.innerHTML = '';
        
        for (let row = 1; row <= config.rows; row++) {
            const rowContainer = document.createElement('div');
            rowContainer.className = 'seat-row';
            
            for (let seat = 1; seat <= config.seatsPerRow; seat++) {
                const letter = String.fromCharCode(64 + seat);
                const seatId = `${row}${letter}`;
                const isOccupied = config.occupiedSeats.includes(seatId);
                const isSelected = selectedSeats.includes(seatId);
                
                const seatElement = document.createElement('div');
                seatElement.className = `seat ${isOccupied ? 'occupied' : 'available'} ${isSelected ? 'selected' : ''}`;
                seatElement.textContent = seatId;
                seatElement.id = `seat-${seatId}`;
                
                if (!isOccupied) {
                    seatElement.addEventListener('click', () => toggleSeat(seatId));
                }
                
                rowContainer.appendChild(seatElement);
                
                // Add aisle after seat B
                if (seat === 2) {
                    rowContainer.appendChild(document.createElement('div')).className = 'aisle';
                }
            }
            
            elements.seatsContainer.appendChild(rowContainer);
        }
    }

    // Handle payment
    async function handlePayment() {
        if (!selectedSeats.length) {
            alert('Please select at least one seat');
            return;
        }
        
        elements.payButton.disabled = true;
        elements.payButton.textContent = 'Processing...';
        
        try {
            const bookingData = {
                booking_id: bookingId,
                seats: selectedSeats,
                total_amount: calculateTotal(),
                base_fare: config.baseFare,
                booking_fee: config.bookingFee,
                tax: config.tax
            };
            
            const response = await fetch('process_seat.php', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(bookingData)
            });
            
            if (!response.ok) throw new Error(`Error: ${response.status}`);
            
            const result = await response.json();
            
            if (result.success) {
                sessionStorage.setItem('bookingData', JSON.stringify(bookingData));
                window.location.href = result.redirect_url || `payment.php?booking_id=${bookingId}`;
            } else {
                throw new Error(result.message || 'Booking failed');
            }
        } catch (error) {
            console.error('Payment error:', error);
            alert(error.message);
        } finally {
            elements.payButton.disabled = false;
            elements.payButton.textContent = 'Proceed to Payment';
        }
    }
</script>
</body>
</html>