<?php
$page_name = 'privacy';  // Set the current page name
include('../pages/header.php');



?>
<style>
  

</style>
</head>

<body>
    <div class="containeryy">
    <h2 class="seat-selection-title">Select Your Seat - Post Bus Malawi</h2>
    <div class="seat-instructions">
        <h3>⚠️ Important Seat Selection Instructions</h3>
        <ul>
            <li>
                <span class="warning">Multiple Seat Selection:</span> 
                Select all desired seats at once before proceeding. If you select a seat and complete payment, then go back to select another seat, the system will not allow you to do so.
            </li>
            <li>
                <span class="warning">Choose Carefully:</span> 
                Make your seat selection thoughtfully. If you make a mistake and want to change seats, the system will not permit modifications.
            </li>
            <li>
                <span class="warning">Note:</span> 
                If you need to change your selection, you must log out and start the booking process again.
            </li>
        </ul>
    </div>

        <div class="bus-layout">
            <div class="bus-front">Driver</div>
            <div class="driver-area">
                <div class="driver-seat">🚌</div>
            </div>
            <div class="seats-container" id="seatsContainer">
                <!-- Seats will be generated by JavaScript -->
            </div>
            <div class="legend">
                <div class="legend-item">
                    <div class="legend-color available-color"></div>
                    <span>Available</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color selected-color"></div>
                    <span>Selected</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color occupied-color"></div>
                    <span>Occupied</span>
                </div>
            </div>
        </div>

        <div class="booking-summary">
            <h3>Booking Summary</h3>
            <div class="malawi-logo">
                <img src="../images/m.webp" alt="Malawi Corporation Logo" class="seatlog">
            </div>
            <div class="price-details">
                <div class="price-row">
                    <span>Base Fare:</span>
                    <span>MWK 35,000</span>
                </div>
                <div class="price-row" id="selectedSeatsText">
                    <span>Selected Seats:</span>
                    <span>None</span>
                </div>
                <div class="price-row">
                    <span>Booking Fee:</span>
                    <span>MWK 2,500</span>
                </div>
                <div class="price-row">
                    <span>Tax:</span>
                    <span>MWK 3,750</span>
                </div>
                <div class="price-row total-price">
                    <span>Total:</span>
                    <span id="totalPrice">MWK 41,250</span>
                </div>
            </div>
        </div>

        <div class="button-container">
            <button type="button" class="back-button" id="backButton">Back to Selection</button>
            <button type="button" class="pay-button" id="payButton" disabled>Proceed to Payment</button>
        </div>
    </div>
    <?php include('../pages/footer.php'); 
    ?>

    <script>
    // Configuration
    const config = {
        rows: 10,
        seatsPerRow: 4,
        baseFare: 35000,
        bookingFee: 2500,
        tax: 3750,
        occupiedSeats: ['1A', '2C', '3D', '5B', '7A', '8D']
    };

    // State
    let selectedSeats = [];
    function getBookingCodeFromUrl() {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get('booking_code');
    }

    // Assign booking code t    o bookingId
    let bookingId = getBookingCodeFromUrl();

    // DOM Elements
    const elements = {
        seatsContainer: document.getElementById('seatsContainer'),
        selectedSeatsText: document.getElementById('selectedSeatsText'),
        totalPrice: document.getElementById('totalPrice'),
        payButton: document.getElementById('payButton'),
        backButton: document.getElementById('backButton')
    };

    // Initialize on DOM load
    document.addEventListener('DOMContentLoaded', () => {
        renderSeats();
        updateSummary();
        
        elements.payButton.addEventListener('click', handlePayment);
        elements.backButton.addEventListener('click', () => {
            window.location.href = 'booking.php';
        });
    });

    // Seat selection handler
    function toggleSeat(seatId) {
        const index = selectedSeats.indexOf(seatId);
        
        if (index === -1) {
            selectedSeats.push(seatId);
        } else {
            selectedSeats.splice(index, 1);
        }
        
        updateSeatUI(seatId);
        updateSummary();
    }

    // Update seat visual state
    function updateSeatUI(seatId) {
        const seatElement = document.getElementById(`seat-${seatId}`);
        if (!seatElement) return;
        
        seatElement.classList.toggle('selected', selectedSeats.includes(seatId));
    }

    // Calculate total price
    function calculateTotal() {
        const seatsTotal = selectedSeats.length * config.baseFare;
        return seatsTotal + config.bookingFee + config.tax;
    }

    // Update summary display
    function updateSummary() {
        const total = calculateTotal();
        const hasSeats = selectedSeats.length > 0;
        
        elements.totalPrice.textContent = `MWK ${total.toLocaleString()}`;
        elements.selectedSeatsText.innerHTML = hasSeats
            ? `<span>Selected Seats (${selectedSeats.length}):</span> 
               <span>${selectedSeats.join(', ')} - MWK ${(selectedSeats.length * config.baseFare).toLocaleString()}</span>`
            : '<span>Selected Seats:</span><span>None</span>';
            
        elements.payButton.disabled = !hasSeats;
    }

    // Render all seats
    function renderSeats() {
        elements.seatsContainer.innerHTML = '';
        
        for (let row = 1; row <= config.rows; row++) {
            const rowContainer = document.createElement('div');
            rowContainer.className = 'seat-row';
            
            for (let seat = 1; seat <= config.seatsPerRow; seat++) {
                const letter = String.fromCharCode(64 + seat);
                const seatId = `${row}${letter}`;
                const isOccupied = config.occupiedSeats.includes(seatId);
                const isSelected = selectedSeats.includes(seatId);
                
                const seatElement = document.createElement('div');
                seatElement.className = `seat ${isOccupied ? 'occupied' : 'available'} ${isSelected ? 'selected' : ''}`;
                seatElement.textContent = seatId;
                seatElement.id = `seat-${seatId}`;
                
                if (!isOccupied) {
                    seatElement.addEventListener('click', () => toggleSeat(seatId));
                }
                
                rowContainer.appendChild(seatElement);
                
                // Add aisle after seat B
                if (seat === 2) {
                    rowContainer.appendChild(document.createElement('div')).className = 'aisle';
                }
            }
            
            elements.seatsContainer.appendChild(rowContainer);
        }
    }

    // Handle payment
    async function handlePayment() {
        if (!selectedSeats.length) {
            alert('Please select at least one seat');
            return;
        }
        
        elements.payButton.disabled = true;
        elements.payButton.textContent = 'Processing...';
        
        try {
            const bookingData = {
                booking_id: bookingId,
                seats: selectedSeats,
                total_amount: calculateTotal(),
                base_fare: config.baseFare,
                booking_fee: config.bookingFee,
                tax: config.tax
            };
            
            const response = await fetch('process_seat.php', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(bookingData)
            });
            
            if (!response.ok) throw new Error(`Error: ${response.status}`);
            
            const result = await response.json();
            
            if (result.success) {
                sessionStorage.setItem('bookingData', JSON.stringify(bookingData));
                window.location.href = result.redirect_url || `payment.php?booking_id=${bookingId}`;
            } else {
                throw new Error(result.message || 'Booking failed');
            }
        } catch (error) {
            console.error('Payment error:', error);
            alert(error.message);
        } finally {
            elements.payButton.disabled = false;
            elements.payButton.textContent = 'Proceed to Payment';
        }
    }
</script>
</body>
</html>